dist: bionic
language: go

branches:
  only:
  - master

git:
  depth: false

jobs:
  include:
  - env: CMD="make validate"
  - env: CMD="make deploy deploytool=helm"
  - env: CMD="make deploy deploytool=operator" DEPLOY=true

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install moreutils docker-ce

services:
  - docker

#addons:
#  apt:
#    packages:
#      - docker-ce
#      - moreutils

script:
  - set -o pipefail;
    $CMD 2>&1 | ts '[%H:%M:%.S]' -s

after_success:
 -  echo "Testing clean up";
    set -o pipefail;
    make cleanup 2>&1 | ts '[%H:%M:%.S]' -s

deploy:
  - provider: script
    script: make release
    on:
      branch: master
      condition: $DEPLOY = true
