---
name: Reporting

on:
  push:
    branches:
      - release-0.16
      - release-*

permissions: {}

jobs:
  vulnerability-scan:
    name: Vulnerability Scanning
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Run Anchore vulnerability scanner
        uses: anchore/scan-action@3343887d815d7b07465f6fdcd395bd66508d486a
        id: scan
        with:
          path: "."
          fail-build: false
      - name: Show Anchore scan SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@9fdb3e49720b44c48891d036bb502feb25684276
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
